mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from mysite import views

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', views.index),
]

#에러가 났는데 그 에러에 대한 컨텍스트를 보여주고 싶을 때 사용
# handler404 = 'mysite.views.error_404_view'

# handler500 = 'mysite.views.error_500_view'

mysite/polls/urls.py
from django.urls import path

from . import views

# added app namespaces
app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/',views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]  

mysite/polls/models.py
from django.db import models

# Create your models here.

mysite/mysite/views.py
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render

def index(request):
    # return HttpResponse("main index")
    # pass
    return render(request, 'main.html')

def error_404_view(request, exception):
    # return HttpResponseNotFound("The page is not found!")
    return render(request, '404.html')

def error_500_view(request,):
    return render(request, '500.html')

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render

def index(request):
    # return HttpResponse("polls index")
    # return HttpResponseRedirect('1')

    # return HttpResponseRedirect(
        # reverse('detail', args=[1]))
    # return HttpResponseRedirect(
    #     reverse('detail', kwargs={'question_id': 1}))
    ctx = {
        "greetings" : "Hello there!",
        "location": {
            "city": "Seoul",
            "country": "South Korea"
        },
        "languages": ["Korean", "English"]
    }
    return render(request, 'polls/main.html', context=ctx)
    

def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):  
    return HttpResponse("You're voting on question %s." % question_id)

mysite/polls/templates/polls/main.html
{% extends 'base.html'%}
{% block content %}
    <h1>
        <a href="{% url 'polls:detail' question_id=10 %}">Question 10</a>
    </h1>
    <h1>{{greetings|lower}}</h1>
    <h2>I am from {{location.city}}, {{location.country}}</h2>
    <h2>I speaks {{languages.0}} and {{languages.1}}</h2>
    <ul>
        {% for lang in languages %}
        <li>{{lang}}</li>
        {% endfor %}

        {% for lang in languages %}
        <li>
            {% if lang == "Korean" %}
            Wow!! You speak Korean!
            {% else %}
            Alright, You speak English!
            {% endif %}
        </li>
        {% endfor %}
    </ul>

    <ul>
        {% for k, v in location.items %}
        <li>{{ k|capfirst }}: {{ v }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

mysite/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <img src="{% static 'mysite/photo.png'%}" alt="photo"/>
{% endblock content %}
        